<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="5" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-01T10:04:40 ART" name="Challenge" finished-at="2022-04-01T10:05:10 ART" duration-ms="29546">
    <groups>
    </groups>
    <test started-at="2022-04-01T10:04:40 ART" name="Lenio Challenge" finished-at="2022-04-01T10:05:10 ART" duration-ms="29546">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="setupBrowser()[pri:0, instance:tests.LoginTest@4f20a5e0]" started-at="2022-04-01T10:04:40 ART" name="setupBrowser" finished-at="2022-04-01T10:04:47 ART" duration-ms="6556" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBrowser -->
        <test-method is-config="true" signature="goToLogin()[pri:0, instance:tests.LoginTest@4f20a5e0]" started-at="2022-04-01T10:04:47 ART" name="goToLogin" finished-at="2022-04-01T10:04:47 ART" duration-ms="466" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToLogin -->
        <test-method signature="testCorrectLoginCredentials()[pri:0, instance:tests.LoginTest@4f20a5e0]" started-at="2022-04-01T10:04:48 ART" name="testCorrectLoginCredentials" finished-at="2022-04-01T10:04:48 ART" duration-ms="727" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCorrectLoginCredentials -->
        <test-method is-config="true" signature="goToLogin()[pri:0, instance:tests.LoginTest@4f20a5e0]" started-at="2022-04-01T10:04:48 ART" name="goToLogin" finished-at="2022-04-01T10:04:48 ART" duration-ms="60" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToLogin -->
        <test-method signature="testIncorrectLoginCredentials()[pri:0, instance:tests.LoginTest@4f20a5e0]" started-at="2022-04-01T10:04:48 ART" name="testIncorrectLoginCredentials" finished-at="2022-04-01T10:04:49 ART" duration-ms="468" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIncorrectLoginCredentials -->
        <test-method is-config="true" signature="tearDownBrowser()[pri:0, instance:tests.LoginTest@4f20a5e0]" started-at="2022-04-01T10:04:49 ART" name="tearDownBrowser" finished-at="2022-04-01T10:04:50 ART" duration-ms="1201" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownBrowser -->
      </class> <!-- tests.LoginTest -->
      <class name="backend.tests.CategoriaTest">
        <test-method signature="testCategoriaEndpoint()[pri:0, instance:backend.tests.CategoriaTest@66bfd864]" started-at="2022-04-01T10:04:58 ART" name="testCategoriaEndpoint" description="Parte 2 Ejercicio 1-a" finished-at="2022-04-01T10:05:06 ART" duration-ms="7771" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCategoriaEndpoint -->
        <test-method signature="testLocalidades()[pri:0, instance:backend.tests.CategoriaTest@66bfd864]" started-at="2022-04-01T10:05:06 ART" name="testLocalidades" description="Parte 2 Ejercicio 1-c" finished-at="2022-04-01T10:05:07 ART" duration-ms="1273" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [27] but found [28]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [27] but found [28]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at backend.tests.CategoriaTest.testLocalidades(CategoriaTest.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLocalidades -->
        <test-method signature="testPedidos()[pri:0, instance:backend.tests.CategoriaTest@66bfd864]" started-at="2022-04-01T10:05:07 ART" name="testPedidos" description="Parte 2 Ejercicio 1-b" finished-at="2022-04-01T10:05:10 ART" duration-ms="2423" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPedidos -->
      </class> <!-- backend.tests.CategoriaTest -->
      <class name="tests.CheckoutTest">
        <test-method is-config="true" signature="setupBrowser()[pri:0, instance:tests.CheckoutTest@1917d90f]" started-at="2022-04-01T10:04:50 ART" name="setupBrowser" finished-at="2022-04-01T10:04:54 ART" duration-ms="3532" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBrowser -->
        <test-method is-config="true" signature="goToLogin()[pri:0, instance:tests.CheckoutTest@1917d90f]" started-at="2022-04-01T10:04:54 ART" name="goToLogin" finished-at="2022-04-01T10:04:54 ART" duration-ms="461" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToLogin -->
        <test-method signature="testCheckout()[pri:0, instance:tests.CheckoutTest@1917d90f]" started-at="2022-04-01T10:04:54 ART" name="testCheckout" finished-at="2022-04-01T10:04:56 ART" duration-ms="1994" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCheckout -->
        <test-method is-config="true" signature="goToLogin()[pri:0, instance:tests.CheckoutTest@1917d90f]" started-at="2022-04-01T10:04:56 ART" name="goToLogin" finished-at="2022-04-01T10:04:56 ART" duration-ms="63" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToLogin -->
        <test-method signature="testCheckoutFail()[pri:0, instance:tests.CheckoutTest@1917d90f]" started-at="2022-04-01T10:04:56 ART" name="testCheckoutFail" finished-at="2022-04-01T10:04:57 ART" duration-ms="1117" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Finish] but found [CHECKOUT: COMPLETE!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Finish] but found [CHECKOUT: COMPLETE!]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at tests.CheckoutTest.testCheckoutFail(CheckoutTest.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCheckoutFail -->
        <test-method is-config="true" signature="tearDownBrowser()[pri:0, instance:tests.CheckoutTest@1917d90f]" started-at="2022-04-01T10:04:57 ART" name="tearDownBrowser" finished-at="2022-04-01T10:04:58 ART" duration-ms="1152" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownBrowser -->
      </class> <!-- tests.CheckoutTest -->
    </test> <!-- Lenio Challenge -->
  </suite> <!-- Challenge -->
</testng-results>
